# Site wide configuration

title:            CEO @ Obeo
locale:           en_US
url:              https://cedric.brun.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
lang: en


collections:
  category:
    output: true # générer la page HTML
    permalink: /:collection/:name/index.html
  tag:
    output: true
    permalink: /:collection/:name/index.html
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Cédric Brun
  avatar: bio-photo-2023.avif
  bio: " Build open-source technologies to enable mission critical tools for complex domains."
  email: cedric.brun@obeo.fr
  disqus-shortname: 
  twitter: bruncedric
  facebook: #username
  google:    
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: cbrun
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: cedric-brun-1367212
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: UCils7-97bgaApBoAlu8_4Ow
  soundcloud: #username
  weibo: #username
  flickr: #username

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: _cache/assets
  cachebust: hard

include: [".htaccess",".well-known"]
exclude:
  - lib
  - config.rb
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - tmp/
  - less
  - talks/etc
  - talks/lib
  - LICENSE
  - vendor

plugins:
      - jekyll-sitemap
      - jekyll-last-modified-at

# Main categories (used in navigation)
main_categories:
  - sirius-web
  - mbse
  - ecore
  - capella
  - obeo
